apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  selector:
    app: ftps
  ports:
    - port: 21
      name: qwe
      protocol: TCP
      targetPort: 21
    - port: 10100
      name: ewq
      protocol: TCP
      targetPort: 10100
    - port: 20
      name: ewqq
      protocol: TCP
      targetPort: 20

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps-service
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10100
        - containerPort: 20
