apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
    - port: 22
      name: ssh
      protocol: TCP
      targetPort: 22

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx-service
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 22
