apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: nginx
  ports:
    - port: 443
      name: port-https
      protocol: TCP
      targetPort: 443
    - port: 80
      name: port-http
      protocol: TCP
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
spec:
  selector:
    matchLabels:
      app: my-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - image: nginx-service
        name: nginx-service
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443