apiVersion: v1
kind: Pod
metadata:
    name: ngin
    labels:
        apps: nginx
spec:
    containers:
        - name: nginx-cont
          image: nginx
          ports: 
            - containerPort: 80
