apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress-service
        name: wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
